google.maps.__gjsload__('geometry', function(_){var Tia=function(a,b){return Math.abs(_.de(b-a,-180,180))},Uia=function(a,b,c,d,e){if(!d){c=Tia(a.lng(),c)/Tia(a.lng(),b.lng());if(!e)return e=Math.sin(_.Vd(a.lat())),e=Math.log((1+e)/(1-e))/2,b=Math.sin(_.Vd(b.lat())),_.Wd(2*Math.atan(Math.exp(e+c*(Math.log((1+b)/(1-b))/2-e)))-Math.PI/2);a=e.fromLatLngToPoint(a);b=e.fromLatLngToPoint(b);return e.fromPointToLatLng(new _.R(a.x+c*(b.x-a.x),a.y+c*(b.y-a.y))).lat()}e=_.Vd(a.lat());a=_.Vd(a.lng());d=_.Vd(b.lat());b=_.Vd(b.lng());c=_.Vd(c);return _.de(_.Wd(Math.atan2(Math.sin(e)*
Math.cos(d)*Math.sin(c-b)-Math.sin(d)*Math.cos(e)*Math.sin(c-a),Math.cos(e)*Math.cos(d)*Math.sin(a-b))),-90,90)},et={containsLocation:function(a,b){a=_.Oe(a);var c=_.de(a.lng(),-180,180),d=!!b.get("geodesic"),e=b.get("latLngs"),f=b.get("map");f=!d&&f?f.getProjection():null;for(var g=!1,h=0,k=e.getLength();h<k;++h)for(var l=e.getAt(h),m=0,p=l.getLength();m<p;++m){var q=l.getAt(m),r=l.getAt((m+1)%p),t=_.de(q.lng(),-180,180),u=_.de(r.lng(),-180,180),w=Math.max(t,u);t=Math.min(t,u);(180<w-t?c>=w||c<t:
c<w&&c>=t)&&Uia(q,r,c,d,f)<a.lat()&&(g=!g)}return g||et.isLocationOnEdge(a,b)}};_.Na("module$exports$mapsapi$geometry$polyGeometry.PolyGeometry.containsLocation",et.containsLocation);
et.isLocationOnEdge=function(a,b,c){a=_.Oe(a);c=c||1E-9;var d=_.de(a.lng(),-180,180),e=b instanceof _.pj,f=!!b.get("geodesic"),g=b.get("latLngs");b=b.get("map");b=!f&&b?b.getProjection():null;for(var h=0,k=g.getLength();h<k;++h)for(var l=g.getAt(h),m=l.getLength(),p=e?m:m-1,q=0;q<p;++q){var r=l.getAt(q),t=l.getAt((q+1)%m),u=_.de(r.lng(),-180,180),w=_.de(t.lng(),-180,180),y=Math.max(u,w),z=Math.min(u,w);if(u=1E-9>=Math.abs(_.de(u-w,-180,180))&&(Math.abs(_.de(u-d,-180,180))<=c||Math.abs(_.de(w-d,-180,
180))<=c)){u=a.lat();w=Math.min(r.lat(),t.lat())-c;var H=Math.max(r.lat(),t.lat())+c;u=u>=w&&u<=H}if(u)return!0;if(180<y-z?d+c>=y||d-c<=z:d+c>=z&&d-c<=y)if(r=Uia(r,t,d,f,b),Math.abs(r-a.lat())<c)return!0}return!1};_.Na("module$exports$mapsapi$geometry$polyGeometry.PolyGeometry.isLocationOnEdge",et.isLocationOnEdge);var ft={computeHeading:function(a,b){a=_.Oe(a);b=_.Oe(b);var c=_.Le(a),d=_.Me(a);a=_.Le(b);b=_.Me(b)-d;return _.de(_.Wd(Math.atan2(Math.sin(b)*Math.cos(a),Math.cos(c)*Math.sin(a)-Math.sin(c)*Math.cos(a)*Math.cos(b))),-180,180)}};_.Na("module$exports$mapsapi$geometry$spherical.Spherical.computeHeading",ft.computeHeading);
ft.computeOffset=function(a,b,c,d){a=_.Oe(a);b/=d||6378137;c=_.Vd(c);var e=_.Le(a);a=_.Me(a);d=Math.cos(b);b=Math.sin(b);var f=Math.sin(e);e=Math.cos(e);var g=d*f+b*e*Math.cos(c);return new _.Ke(_.Wd(Math.asin(g)),_.Wd(a+Math.atan2(b*e*Math.sin(c),d-f*g)))};_.Na("module$exports$mapsapi$geometry$spherical.Spherical.computeOffset",ft.computeOffset);
ft.computeOffsetOrigin=function(a,b,c,d){a=_.Oe(a);c=_.Vd(c);b/=d||6378137;d=Math.cos(b);var e=Math.sin(b)*Math.cos(c);b=Math.sin(b)*Math.sin(c);c=Math.sin(_.Le(a));var f=e*e*d*d+d*d*d*d-d*d*c*c;if(0>f)return null;var g=e*c+Math.sqrt(f);g/=d*d+e*e;var h=(c-e*g)/d;g=Math.atan2(h,g);if(g<-Math.PI/2||g>Math.PI/2)g=e*c-Math.sqrt(f),g=Math.atan2(h,g/(d*d+e*e));if(g<-Math.PI/2||g>Math.PI/2)return null;a=_.Me(a)-Math.atan2(b,d*Math.cos(g)-e*Math.sin(g));return new _.Ke(_.Wd(g),_.Wd(a))};
_.Na("module$exports$mapsapi$geometry$spherical.Spherical.computeOffsetOrigin",ft.computeOffsetOrigin);
ft.interpolate=function(a,b,c){a=_.Oe(a);b=_.Oe(b);var d=_.Le(a),e=_.Me(a),f=_.Le(b),g=_.Me(b),h=Math.cos(d),k=Math.cos(f);b=ft.Xq(a,b);var l=Math.sin(b);if(1E-6>l)return new _.Ke(a.lat(),a.lng());a=Math.sin((1-c)*b)/l;c=Math.sin(c*b)/l;b=a*h*Math.cos(e)+c*k*Math.cos(g);e=a*h*Math.sin(e)+c*k*Math.sin(g);return new _.Ke(_.Wd(Math.atan2(a*Math.sin(d)+c*Math.sin(f),Math.sqrt(b*b+e*e))),_.Wd(Math.atan2(e,b)))};_.Na("module$exports$mapsapi$geometry$spherical.Spherical.interpolate",ft.interpolate);
ft.Xq=function(a,b){var c=_.Le(a);a=_.Me(a);var d=_.Le(b);b=_.Me(b);return 2*Math.asin(Math.sqrt(Math.pow(Math.sin((c-d)/2),2)+Math.cos(c)*Math.cos(d)*Math.pow(Math.sin((a-b)/2),2)))};ft.computeDistanceBetween=function(a,b,c){a=_.Oe(a);b=_.Oe(b);c=c||6378137;return ft.Xq(a,b)*c};_.Na("module$exports$mapsapi$geometry$spherical.Spherical.computeDistanceBetween",ft.computeDistanceBetween);
ft.computeLength=function(a,b){b=b||6378137;var c=0;a instanceof _.ti&&(a=a.getArray());for(var d=0,e=a.length-1;d<e;++d)c+=ft.computeDistanceBetween(a[d],a[d+1],b);return c};_.Na("module$exports$mapsapi$geometry$spherical.Spherical.computeLength",ft.computeLength);ft.computeArea=function(a,b){return Math.abs(ft.computeSignedArea(a,b))};_.Na("module$exports$mapsapi$geometry$spherical.Spherical.computeArea",ft.computeArea);
ft.ht=function(a){var b=gt;if(isFinite(a)){var c=a%360;a=Math.round(c/90);c-=90*a;if(30===c||-30===c){c=.5*_.v(Math,"sign").call(Math,c);var d=Math.sqrt(.75)}else 45===c||-45===c?(c=_.v(Math,"sign").call(Math,c)*Math.SQRT1_2,d=Math.SQRT1_2):(d=c/180*Math.PI,c=Math.sin(d),d=Math.cos(d));switch(a&3){case 0:b[0]=c;b[1]=d;break;case 1:b[0]=d;b[1]=-c;break;case 2:b[0]=-c;b[1]=-d;break;default:b[0]=-d,b[1]=c}}else b[0]=NaN,b[1]=NaN};var gt=Array(2);
ft.ks=function(a,b){ft.ht(a.lat());var c=_.A(gt),d=c.next().value;c=c.next().value;ft.ht(a.lng());var e=_.A(gt);a=e.next().value;e=e.next().value;b[0]=c*e;b[1]=c*a;b[2]=d};ft.Ny=function(a){for(var b=0,c=1;c<a.length;++c)Math.abs(a[c])<Math.abs(a[b])&&(b=c);c=[0,0,0];c[b]=1;a=[a[1]*c[2]-a[2]*c[1],a[2]*c[0]-a[0]*c[2],a[0]*c[1]-a[1]*c[0]];b=_.v(Math,"hypot").apply(Math,_.ma(a));return[a[0]/b,a[1]/b,a[2]/b]};ft.Cv=function(a){for(var b=0;3>b;++b)if(0!==a[b]){if(0>a[b])return[-a[0],-a[1],-a[2]];break}return a};
ft.Os=function(a,b,c){var d=a[0]*b[1]+a[1]*b[0]+a[2]*b[3]-a[3]*b[2],e=a[0]*b[2]-a[1]*b[3]+a[2]*b[0]+a[3]*b[1],f=a[0]*b[3]+a[1]*b[2]-a[2]*b[1]+a[3]*b[0];c[0]=a[0]*b[0]-a[1]*b[1]-a[2]*b[2]-a[3]*b[3];c[1]=d;c[2]=e;c[3]=f};
ft.zp=function(a,b,c){var d=a[0]-b[0],e=a[1]-b[1],f=a[2]-b[2],g=a[0]+b[0],h=a[1]+b[1],k=a[2]+b[2],l=g*g+h*h+k*k,m=e*k-f*h;f=f*g-d*k;d=d*h-e*g;e=l*l+m*m+f*f+d*d;0!==e?(b=Math.sqrt(e),c[0]=l/b,c[1]=m/b,c[2]=f/b,c[3]=d/b):(l=ft.Ny(ft.Cv([a[0]-b[0],a[1]-b[1],a[2]-b[2]])),m=Array(4),ft.zp(a,l,m),a=Array(4),ft.zp(l,b,a),ft.Os(a,m,c))};
ft.computeSignedArea=function(a,b){b=b||6378137;a instanceof _.ti&&(a=a.getArray());a=(0,_.Lf)(a);if(0===a.length)return 0;var c=Array(4),d=Array(3),e=[1,0,0,0],f=Array(3);ft.ks(a[a.length-1],f);for(var g=0;g<a.length;++g){ft.ks(a[g],d);ft.zp(f,d,c);ft.Os(c,e,e);var h=_.A(d);f[0]=h.next().value;f[1]=h.next().value;f[2]=h.next().value}d=_.A(f);a=d.next().value;c=d.next().value;d=d.next().value;h=_.A(e);e=h.next().value;f=h.next().value;g=h.next().value;h=h.next().value;return 2*Math.atan2(a*f+c*g+
d*h,e)*b*b};_.Na("module$exports$mapsapi$geometry$spherical.Spherical.computeSignedArea",ft.computeSignedArea);ft.Yq=function(a,b,c){return ft.computeSignedArea([a,b,c],1)};ft.bB=function(a,b,c){return Math.abs(ft.Yq(a,b,c))};ft.kB=function(a,b,c){return _.v(Math,"sign").call(Math,ft.Yq(a,b,c))};var ht={decodePath:function(a){var b=_.Xd(a),c=Array(Math.floor(a.length/2)),d=0,e=0,f=0,g;for(g=0;d<b;++g){var h=1,k=0;do{var l=a.charCodeAt(d++)-63-1;h+=l<<k;k+=5}while(31<=l);e+=h&1?~(h>>1):h>>1;h=1;k=0;do l=a.charCodeAt(d++)-63-1,h+=l<<k,k+=5;while(31<=l);f+=h&1?~(h>>1):h>>1;c[g]=new _.Ke(1E-5*e,1E-5*f,!0)}c.length=g;return c}};_.Na("module$exports$mapsapi$poly$polylineCodec.PolylineCodec.decodePath",ht.decodePath);
ht.encodePath=function(a){a instanceof _.ti&&(a=a.getArray());a=(0,_.Lf)(a);return ht.Ry(a,function(b){return[Math.round(1E5*b.lat()),Math.round(1E5*b.lng())]})};_.Na("module$exports$mapsapi$poly$polylineCodec.PolylineCodec.encodePath",ht.encodePath);ht.Ry=function(a,b){for(var c=[],d=[0,0],e,f=0,g=_.Xd(a);f<g;++f)e=b?b(a[f]):a[f],ht.Hs(e[0]-d[0],c),ht.Hs(e[1]-d[1],c),d=e;return c.join("")};ht.Hs=function(a,b){ht.Sy(0>a?~(a<<1):a<<1,b)};
ht.Sy=function(a,b){for(;32<=a;)b.push(String.fromCharCode((32|a&31)+63)),a>>=5;b.push(String.fromCharCode(a+63))};var Via={encoding:ht,spherical:ft,poly:et};_.C.google.maps.geometry=Via;_.ff("geometry",Via);});
